version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "5432"
    environment:
      - MYSQL_DATABASE=SIGS_development
      - MYSQL_ALLOW_EMPTY_PASSWORD='true'

  web:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    command: /bin/bash -l -c "chmod +x start-dev.sh && ./start-dev.sh"
    volumes:
      - ./SIGS:/SIGS-MES
    ports:
      - "3000:3000"
    links:
      - db:mysql
    depends_on:
      - db
